name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Extract commit data
      uses: rlespinasse/git-commit-data-action@v1

    - name: Raise Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "auto-pr-branch"
        base: main
        title: "Automated Pull Request"
        committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL}}">
        author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL}}">  
        body: 
          This pull request was automatically created by a GitHub Actions workflow.
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
